# Usamos una imagen base de Nginx
FROM nginx:latest

# Copiamos los archivos compilados de la aplicación Angular a Nginx
COPY ./ticket-sale/dist/angular-app /usr/share/nginx/html

# Copiamos el archivo de configuración personalizado de Nginx
COPY ./nginx-config/nginx.conf /etc/nginx/conf.d/default.conf