version: '3'
services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile-web-server
    ports:
      - "4000:4000"
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile-angular-app
    ports:
      - "8080:80"
